### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by 0xlethe** [Aboa123/VrchatTogether#6]
우선 css를 styled-components로 대체합니다.
추가로 중복해서 만들어낸 로직은 함수로 묶고, 함수형 프로그래밍을 지향합니다.
일부 컴포넌트의 경우 모듈화가 가능하지만, 하지 않았던 부분에 대해 수정을 진행합니다.

**Comment by Aboa123** [comment]
다크모드 출시 이후 진행필요합니다
